apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-and-test
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        rm -rf /workspace/data/*
    - name: nose
      image: python:3.9
      script: |
        nosetests