name: CI Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint with flake8
        run: flake8 .
      - name: Run unit test with nose
        run: nosetests